[program:mamun-horizon]
process_name=%(program_name)s
command=php /var/www/html/mamun-automobiles-backend/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/mamun-automobiles-backend/storage/logs/horizon.log
stopwaitsecs=3600

[program:mamun-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/mamun-automobiles-backend/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/html/mamun-automobiles-backend/storage/logs/worker.log
stopwaitsecs=60
