<template>
  <div class="space-y-6">
    <!-- State 1: No Quotation exists -->
    <div v-if="!quotation" class="bg-white shadow-sm rounded-xl border border-slate-200 p-8 text-center">
      <div class="max-w-md mx-auto space-y-4">
        <div class="inline-flex p-3 bg-indigo-50 rounded-full text-indigo-600">
          <svg class="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
          </svg>
        </div>
        <h3 class="text-lg font-semibold text-slate-900">Generate Quotation Draft</h3>
        <p class="text-sm text-slate-500">No quotation has been generated for this Job Card yet. Generate a versioned draft applying the corporate contract pricing engine.</p>
        <button
          @click="initiateQuotationDraft"
          :disabled="creatingDraft"
          class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-semibold rounded-lg shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 transition-all"
        >
          {{ creatingDraft ? 'Generating Draft...' : 'Generate Corporate Quotation Draft' }}
        </button>
      </div>
    </div>

    <!-- State 2: Quotation Sheet -->
    <div v-else class="grid grid-cols-1 xl:grid-cols-3 gap-6">
      <!-- Quotation details & list of items -->
      <div class="xl:col-span-2 space-y-6">
        <div class="bg-white shadow-sm rounded-xl border border-slate-200 overflow-hidden">
          <!-- Header -->
          <div class="px-6 py-5 border-b border-slate-200 bg-slate-50 flex justify-between items-center flex-wrap gap-4">
            <div>
              <div class="flex items-center space-x-3">
                <h3 class="text-lg font-bold text-slate-900">{{ quotation.quotation_number }}</h3>
                <span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-100 text-indigo-800">
                  Version {{ quotation.version }}
                </span>
                <span :class="getQuotationStatusClass(quotation.status)" class="px-2.5 py-0.5 rounded-full text-xs font-semibold capitalize">
                  {{ quotation.status?.replace('_', ' ') }}
                </span>
              </div>
              <p class="text-xs text-slate-500 mt-1">Generated by corporate billing system</p>
            </div>
            <div class="flex space-x-2">
              <button
                v-if="quotation.status === 'draft' || quotation.status === 'revised'"
                @click="openApprovalModal"
                class="inline-flex items-center px-3.5 py-1.5 border border-transparent text-xs font-semibold rounded bg-green-600 hover:bg-green-700 text-white shadow-sm"
              >
                Record Customer Action
              </button>
              <button
                v-if="quotation.status === 'draft' || quotation.status === 'revised'"
                @click="openRevisionModal"
                class="inline-flex items-center px-3.5 py-1.5 border border-slate-300 text-xs font-medium rounded bg-white hover:bg-slate-50 text-slate-700 shadow-sm"
              >
                Revise Quotation
              </button>
            </div>
          </div>

          <!-- List Items -->
          <div class="p-6 space-y-6">
            <!-- Product Lines -->
            <div>
              <h4 class="text-sm font-bold text-slate-800 uppercase tracking-wider mb-3">Product Line Items</h4>
              <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-slate-200">
                  <thead class="bg-slate-50">
                    <tr>
                      <th class="px-4 py-2 text-left text-xs font-semibold text-slate-500">Product Name</th>
                      <th class="px-4 py-2 text-left text-xs font-semibold text-slate-500">Ownership</th>
                      <th class="px-4 py-2 text-right text-xs font-semibold text-slate-500">Qty</th>
                      <th class="px-4 py-2 text-right text-xs font-semibold text-slate-500">Contract Rate</th>
                      <th class="px-4 py-2 text-right text-xs font-semibold text-slate-500">Total Billed</th>
                      <th class="px-4 py-2 class text-center text-xs font-semibold text-slate-500">Action</th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-slate-200">
                    <tr v-for="item in productItems" :key="item.id">
                      <td class="px-4 py-3 text-sm text-slate-900 font-medium">
                        {{ item.part?.name || 'Part' }}
                      </td>
                      <td class="px-4 py-3 text-sm">
                        <span :class="item.source_type === 'workshop_supplied' ? 'bg-blue-100 text-blue-800' : 'bg-orange-100 text-orange-800'" class="px-2 py-0.5 rounded text-xs font-bold">
                          {{ item.source_type === 'workshop_supplied' ? 'Workshop Supplied' : 'Customer Supplied ($0.00)' }}
                        </span>
                      </td>
                      <td class="px-4 py-3 text-sm text-slate-900 text-right">{{ item.quantity }}</td>
                      <td class="px-4 py-3 text-sm text-slate-900 text-right">
                        {{ formatCurrency(item.source_type === 'workshop_supplied' ? item.unit_price : 0) }}
                      </td>
                      <td class="px-4 py-3 text-sm font-bold text-slate-900 text-right">
                        {{ formatCurrency(item.source_type === 'workshop_supplied' ? item.quantity * item.unit_price : 0) }}
                      </td>
                      <td class="px-4 py-3 text-sm text-center">
                        <button
                          v-if="quotation.status === 'draft' || quotation.status === 'revised'"
                          @click="promptRemoveItem(item)"
                          class="text-red-600 hover:text-red-900 text-xs font-semibold"
                        >
                          Remove
                        </button>
                        <span v-else class="text-slate-400 text-xs">Locked</span>
                      </td>
                    </tr>
                    <tr v-if="productItems.length === 0">
                      <td colspan="6" class="px-4 py-4 text-center text-slate-500 text-sm">No products added.</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <!-- Service Lines -->
            <div>
              <h4 class="text-sm font-bold text-slate-800 uppercase tracking-wider mb-3">Service Line Items</h4>
              <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-slate-200">
                  <thead class="bg-slate-50">
                    <tr>
                      <th class="px-4 py-2 text-left text-xs font-semibold text-slate-500">Service Description</th>
                      <th class="px-4 py-2 class text-right text-xs font-semibold text-slate-500">Est. Hours</th>
                      <th class="px-4 py-2 class text-right text-xs font-semibold text-slate-500">Labor Charge</th>
                      <th class="px-4 py-2 class text-center text-xs font-semibold text-slate-500">Action</th>
                    </tr>
                  </thead>
                  <tbody class="divide-y divide-slate-200">
                    <tr v-for="item in serviceItems" :key="item.id">
                      <td class="px-4 py-3 text-sm text-slate-900 font-medium">{{ item.service_name }}</td>
                      <td class="px-4 py-3 text-sm text-slate-900 text-right">{{ item.estimated_hours }} hrs</td>
                      <td class="px-4 py-3 text-sm font-bold text-slate-900 text-right">{{ formatCurrency(item.labor_cost) }}</td>
                      <td class="px-4 py-3 text-sm text-center">
                        <button
                          v-if="quotation.status === 'draft' || quotation.status === 'revised'"
                          @click="promptRemoveItem(item)"
                          class="text-red-600 hover:text-red-900 text-xs font-semibold"
                        >
                          Remove
                        </button>
                        <span v-else class="text-slate-400 text-xs">Locked</span>
                      </td>
                    </tr>
                    <tr v-if="serviceItems.length === 0">
                      <td colspan="4" class="px-4 py-4 text-center text-slate-500 text-sm">No services added.</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <!-- Removal Prompt Modal (Auditable Deletion) -->
        <div v-if="showRemovalModal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50">
          <div class="bg-white rounded-xl shadow-xl max-w-md w-full border border-slate-200 p-6 space-y-4 mx-4">
            <h3 class="text-lg font-bold text-slate-900 flex items-center">
              <svg class="w-5 h-5 mr-2 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path>
              </svg>
              Auditable Item Removal
            </h3>
            <p class="text-sm text-slate-500">To comply with enterprise workshop safety rules, please supply the deletion audit reason (min 10 characters).</p>
            <textarea
              v-model="removalReason"
              rows="3"
              required
              class="block w-full rounded-lg border-slate-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm"
              placeholder="Provide reason e.g. Customer decided to purchase their own spark plugs, or mechanic diagnosed the brake pad wear as within tolerance..."
            ></textarea>
            <p class="text-xs text-red-600 font-bold" v-if="removalReason.length < 10 && removalReason.length > 0">
              Reason is too short! Must be at least 10 characters (currently: {{ removalReason.length }}).
            </p>
            <div class="flex justify-end space-x-3">
              <button
                type="button"
                @click="showRemovalModal = false"
                class="px-4 py-2 border border-slate-300 text-sm font-semibold rounded-lg bg-white hover:bg-slate-50 text-slate-700"
              >
                Cancel
              </button>
              <button
                type="button"
                @click="removeItemConfirmed"
                :disabled="removalReason.length < 10 || deletingItem"
                class="px-4 py-2 border border-transparent text-sm font-semibold rounded-lg bg-red-600 hover:bg-red-700 text-white disabled:opacity-50"
              >
                {{ deletingItem ? 'Removing...' : 'Delete & Log Audit' }}
              </button>
            </div>
          </div>
        </div>

        <!-- Approval Wizard Modal -->
        <div v-if="showApprovalModal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50">
          <div class="bg-white rounded-xl shadow-xl max-w-lg w-full border border-slate-200 p-6 space-y-4 mx-4 overflow-y-auto max-h-[90vh]">
            <h3 class="text-lg font-bold text-slate-900">Record Customer Approval</h3>
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-slate-700 mb-1">Approved By Name *</label>
                <input
                  v-model="approvalForm.approved_by"
                  type="text"
                  required
                  placeholder="e.g. Mr. Mamunur Rahman (Customer)"
                  class="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                />
              </div>

              <div>
                <label class="block text-sm font-medium text-slate-700 mb-1">Approval Type *</label>
                <select
                  v-model="approvalForm.status"
                  required
                  class="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                >
                  <option value="approved">Fully Approved (Generate Work Order)</option>
                  <option value="partially_approved">Partially Approved (Select specific lines)</option>
                  <option value="rejected">Rejected (Cancel Job Card)</option>
                </select>
              </div>

              <!-- Partial Approval Item Selector -->
              <div v-if="approvalForm.status === 'partially_approved'" class="border border-slate-100 p-3 rounded bg-slate-50 space-y-2">
                <label class="block text-xs font-bold text-slate-600 uppercase mb-2">Check Approved Items Only</label>
                <div v-for="item in quotation.items" :key="item.id" class="flex items-center space-x-3 text-sm">
                  <input
                    type="checkbox"
                    :value="item.id"
                    v-model="approvalForm.approved_items"
                    class="rounded text-indigo-600 focus:ring-indigo-500"
                  />
                  <span class="text-slate-900 font-medium">
                    {{ item.item_type === 'product' ? (item.part?.name || 'Product') : item.service_name }}
                    -
                    {{ formatCurrency(item.item_type === 'product' ? item.quantity * item.unit_price : item.labor_cost) }}
                  </span>
                </div>
              </div>

              <div>
                <label class="block text-sm font-medium text-slate-700 mb-1">Digital Signature Drawing Mockup *</label>
                <div class="h-28 bg-slate-50 border border-slate-300 border-dashed rounded-lg flex items-center justify-center cursor-pointer text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors">
                  <span>Draw or Tap to Sign Representative Signature</span>
                </div>
              </div>

              <div>
                <label class="block text-sm font-medium text-slate-700 mb-1">Interaction Notes</label>
                <textarea
                  v-model="approvalForm.notes"
                  rows="2"
                  placeholder="Record customer comments, call timestamps, etc..."
                  class="block w-full rounded-lg border-slate-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                ></textarea>
              </div>
            </div>
            <div class="flex justify-end space-x-3 pt-4 border-t border-slate-100">
              <button
                type="button"
                @click="showApprovalModal = false"
                class="px-4 py-2 border border-slate-300 text-sm font-semibold rounded-lg bg-white hover:bg-slate-50 text-slate-700"
              >
                Close
              </button>
              <button
                type="button"
                @click="submitApproval"
                :disabled="approving || !approvalForm.approved_by"
                class="px-4 py-2 border border-transparent text-sm font-semibold rounded-lg bg-green-600 hover:bg-green-700 text-white disabled:opacity-50"
              >
                {{ approving ? 'Recording Approval...' : 'Confirm Action' }}
              </button>
            </div>
          </div>
        </div>

        <!-- Add Item Panel (Dynamic Customer pricing auto load) -->
        <div v-if="quotation.status === 'draft' || quotation.status === 'revised'" class="bg-white shadow-sm rounded-xl border border-slate-200 p-6 space-y-4">
          <h4 class="text-sm font-bold text-slate-800 uppercase tracking-wider">Add Line Item with pricing engine autofill</h4>
          <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label class="block text-xs text-slate-500 mb-1">Item Type</label>
              <select v-model="newItem.item_type" class="block w-full rounded border-slate-300 shadow-sm sm:text-sm">
                <option value="product">Product (Parts/Materials)</option>
                <option value="service">Service Task (Labor)</option>
              </select>
            </div>

            <div v-if="newItem.item_type === 'product'">
              <label class="block text-xs text-slate-500 mb-1">Product (Part)</label>
              <select v-model="newItem.part_id" @change="calculatePricingEngineRate" class="block w-full rounded border-slate-300 shadow-sm sm:text-sm">
                <option value="">Select Part...</option>
                <option v-for="part in partsList" :key="part.id" :value="part.id">
                  {{ part.name }} (SKU: {{ part.sku }})
                </option>
              </select>
            </div>

            <div v-else>
              <label class="block text-xs text-slate-500 mb-1">Service Description</label>
              <input
                v-model="newItem.service_name"
                @blur="calculatePricingEngineRate"
                type="text"
                placeholder="e.g. Engine Diagnostics Scan"
                class="block w-full rounded border-slate-300 shadow-sm sm:text-sm"
              />
            </div>

            <div>
              <label class="block text-xs text-slate-500 mb-1">Price Rate (Auto Filled)</label>
              <input
                v-model.number="newItem.price"
                type="number"
                class="block w-full rounded border-slate-300 shadow-sm sm:text-sm"
              />
            </div>

            <div>
              <label class="block text-xs text-slate-500 mb-1">Qty / Est. Hours</label>
              <input
                v-model.number="newItem.quantity"
                type="number"
                class="block w-full rounded border-slate-300 shadow-sm sm:text-sm"
              />
            </div>
          </div>

          <div class="flex justify-between items-center pt-2">
            <span class="text-xs text-indigo-600 font-semibold flex items-center" v-if="calculatingRate">
              <svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-indigo-600" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Pricing engine looking up contract fallback rates...
            </span>
            <span v-else class="text-xs text-green-600 font-semibold">
              ✔ Pricing rate dynamically loaded
            </span>
            <button
              @click="addNewItemLine"
              class="inline-flex justify-center px-4 py-2 border border-transparent text-xs font-semibold rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm"
            >
              Add Item to Draft
            </button>
          </div>
        </div>
      </div>

      <!-- Totals & Version snapshots audit log -->
      <div class="xl:col-span-1 space-y-6">
        <!-- AI Quotation Pricing Assistant -->
        <AiQuotationAssistant 
          v-if="quotation"
          :quotation-items="quotation.items || []" 
          :discount-amount="quotation.discount || 0" 
          :total-amount="(quotation.total_product_cost || 0) + (quotation.total_labor_cost || 0)" 
        />

        <!-- Summary Panel -->
        <div class="bg-white shadow-sm rounded-xl border border-slate-200 overflow-hidden">
          <div class="px-6 py-4 border-b border-slate-200 bg-slate-50">
            <h3 class="text-sm font-bold text-slate-800 uppercase tracking-wider">Quotation Summary</h3>
          </div>
          <div class="p-6 space-y-4">
            <dl class="space-y-3">
              <div class="flex justify-between text-sm">
                <dt class="text-slate-500">Products Total:</dt>
                <dd class="font-bold text-slate-900">{{ formatCurrency(quotation.total_product_cost) }}</dd>
              </div>
              <div class="flex justify-between text-sm">
                <dt class="text-slate-500">Service labor Total:</dt>
                <dd class="font-bold text-slate-900">{{ formatCurrency(quotation.total_labor_cost) }}</dd>
              </div>
              <div class="flex justify-between text-sm pt-2 border-t border-slate-100">
                <dt class="text-slate-500">Discount:</dt>
                <dd class="font-bold text-red-600">- {{ formatCurrency(quotation.discount) }}</dd>
              </div>
              <div class="flex justify-between text-sm">
                <dt class="text-slate-500">Vat rate (15%):</dt>
                <dd class="font-bold text-slate-900">+ {{ formatCurrency(quotation.tax) }}</dd>
              </div>
              <div class="flex justify-between text-base font-bold pt-3 border-t border-slate-200">
                <dt class="text-slate-900">Grand Total:</dt>
                <dd class="text-indigo-600">{{ formatCurrency(quotation.grand_total) }}</dd>
              </div>
            </dl>
          </div>
        </div>

        <!-- Snapshot History Log -->
        <div class="bg-white shadow-sm rounded-xl border border-slate-200 overflow-hidden">
          <div class="px-6 py-4 border-b border-slate-200 bg-slate-50">
            <h3 class="text-sm font-bold text-slate-800 uppercase tracking-wider">Revision Version Snapshot Logs</h3>
          </div>
          <div class="p-6">
            <div v-if="!quotation.snapshots || quotation.snapshots.length === 0" class="text-center py-4">
              <p class="text-xs text-slate-500">This is the initial version of this quotation sheet. No revisions generated.</p>
            </div>
            <div v-else class="space-y-4">
              <div v-for="snap in quotation.snapshots" :key="snap.id" class="border-l-2 border-indigo-500 pl-3 py-1 space-y-1">
                <div class="text-xs font-bold text-slate-900">Version {{ snap.version }} Snapshot</div>
                <div class="text-[10px] text-slate-400">Captured on {{ formatDate(snap.created_at) }} by {{ snap.created_by?.name || 'Advisor' }}</div>
                <div class="text-xs text-slate-600 font-semibold">{{ snap.snapshot_data?.notes || 'Internal revision snapshot.' }}</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Deletion Audits Log -->
        <div class="bg-white shadow-sm rounded-xl border border-slate-200 overflow-hidden">
          <div class="px-6 py-4 border-b border-slate-200 bg-slate-50">
            <h3 class="text-sm font-bold text-slate-800 uppercase tracking-wider">Removed Items Deletion Audits</h3>
          </div>
          <div class="p-6">
            <div v-if="!quotation.removed_items || quotation.removed_items.length === 0" class="text-center py-4">
              <p class="text-xs text-slate-500">All added items intact. No lines removed from this sheet.</p>
            </div>
            <div v-else class="space-y-4">
              <div v-for="audit in quotation.removed_items" :key="audit.id" class="bg-red-50/50 border-l-2 border-red-500 pl-3 py-1.5 space-y-1 rounded-r">
                <div class="text-xs font-bold text-slate-900 flex justify-between">
                  <span>{{ audit.item_name }}</span>
                  <span class="text-red-700 font-medium">{{ formatCurrency(audit.previous_price) }}</span>
                </div>
                <div class="text-[10px] text-slate-400">Removed on {{ formatDate(audit.removed_at) }} by {{ audit.removed_by?.name || 'Advisor' }}</div>
                <div class="text-xs text-red-800 italic mt-1 bg-white p-1 border border-red-100 rounded">
                  "{{ audit.removal_reason }}"
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import api from '../../../services/api';
import { useToastStore } from '../../../stores/toast';
import AiQuotationAssistant from '../../../components/dashboard/AiQuotationAssistant.vue';

const props = defineProps({
  jobCard: {
    type: Object,
    required: true,
  }
});

const emit = defineEmits(['updated']);

const toast = useToastStore();
const quotation = ref(null);
const loading = ref(true);
const creatingDraft = ref(false);

const partsList = ref([]);
const calculatingRate = ref(false);

// Form definitions
const newItem = ref({
  item_type: 'product',
  part_id: '',
  service_name: '',
  price: 0,
  quantity: 1,
});

const showRemovalModal = ref(false);
const itemToRemove = ref(null);
const removalReason = ref('');
const deletingItem = ref(false);

const showApprovalModal = ref(false);
const approving = ref(false);
const approvalForm = ref({
  status: 'approved',
  approved_by: '',
  notes: '',
  approved_items: [],
  rejected_items: [],
});

const productItems = computed(() => {
  if (!quotation.value || !quotation.value.items) return [];
  return quotation.value.items.filter(i => i.item_type === 'product');
});

const serviceItems = computed(() => {
  if (!quotation.value || !quotation.value.items) return [];
  return quotation.value.items.filter(i => i.item_type === 'service');
});

const fetchQuotation = async () => {
  try {
    const response = await api.get('/quotations', { params: { job_card_id: props.jobCard.id } });
    if (response.data.data && response.data.data.length > 0) {
      // Load details of the first quotation
      const details = await api.get(`/quotations/${response.data.data[0].id}`);
      quotation.value = details.data.data;
    } else {
      quotation.value = null;
    }
  } catch (err) {
    console.error('Failed to load quotation', err);
  } finally {
    loading.value = false;
  }
};

const fetchPartsList = async () => {
  try {
    const response = await api.get('/parts');
    partsList.value = response.data.data;
  } catch (err) {
    console.error('Failed to fetch parts', err);
  }
};

onMounted(() => {
  fetchQuotation();
  fetchPartsList();
});

const initiateQuotationDraft = async () => {
  creatingDraft.value = true;
  try {
    // Generate quotation with mock intake lines based on diagnosis
    const response = await api.post('/quotations', {
      job_card_id: props.jobCard.id,
      notes: 'Initial generated quotation based on diagnostics findings.',
      discount: 0,
      tax: 0,
      items: [
        {
          item_type: 'service',
          service_name: 'Diagnostic Scan & Complete Fault Analysis',
          estimated_hours: 1.5,
          source_type: 'workshop_supplied',
        }
      ]
    });
    quotation.value = response.data.data;
    toast.success('Quotation draft successfully generated!');
    emit('updated');
  } catch (err) {
    toast.error('Failed to generate quotation draft');
  } finally {
    creatingDraft.value = false;
  }
};

const calculatePricingEngineRate = async () => {
  if (newItem.value.item_type === 'product' && !newItem.value.part_id) return;
  if (newItem.value.item_type === 'service' && !newItem.value.service_name) return;

  calculatingRate.value = true;
  try {
    const response = await api.get(`/customers/${props.jobCard.customer_id}/pricing/calculate`, {
      params: {
        part_id: newItem.value.part_id || undefined,
        labor_service_name: newItem.value.service_name || undefined,
      }
    });
    newItem.value.price = response.data.data.price;
  } catch (err) {
    console.error('Calculated rate lookups failed', err);
  } finally {
    calculatingRate.value = false;
  }
};

const addNewItemLine = async () => {
  try {
    // Modify quotation to add new line, triggering a revision automatically!
    const revisionItems = quotation.value.items.map(item => ({
      item_type: item.item_type,
      part_id: item.part_id,
      service_name: item.service_name,
      quantity: item.quantity,
      unit_price: item.unit_price,
      labor_cost: item.labor_cost,
      estimated_hours: item.estimated_hours,
      source_type: item.source_type,
    }));

    revisionItems.push({
      item_type: newItem.value.item_type,
      part_id: newItem.value.part_id || undefined,
      service_name: newItem.value.service_name || undefined,
      quantity: newItem.value.quantity,
      unit_price: newItem.value.item_type === 'product' ? newItem.value.price : undefined,
      labor_cost: newItem.value.item_type === 'service' ? newItem.value.price : undefined,
      estimated_hours: newItem.value.item_type === 'service' ? newItem.value.quantity : undefined,
      source_type: 'workshop_supplied',
    });

    const response = await api.put(`/quotations/${quotation.value.id}/revise`, {
      reason: 'Additional line item added to quotation draft.',
      items: revisionItems,
    });

    quotation.value = response.data.data;
    toast.success('Line item added successfully!');
    
    // Reset inputs
    newItem.value.part_id = '';
    newItem.value.service_name = '';
    newItem.value.price = 0;
    newItem.value.quantity = 1;
  } catch (err) {
    toast.error('Failed to add item line');
  }
};

const promptRemoveItem = (item) => {
  itemToRemove.value = item;
  removalReason.value = '';
  showRemovalModal.value = true;
};

const removeItemConfirmed = async () => {
  deletingItem.value = true;
  try {
    await api.delete(`/quotation-items/${itemToRemove.value.id}`, {
      data: { reason: removalReason.value }
    });
    toast.success('Quotation item removed and logged.');
    showRemovalModal.value = false;
    await fetchQuotation();
  } catch (err) {
    toast.error(err.response?.data?.message || 'Failed to remove item');
  } finally {
    deletingItem.value = false;
  }
};

const openApprovalModal = () => {
  approvalForm.value.approved_by = props.jobCard.customer?.name || '';
  approvalForm.value.approved_items = quotation.value.items.map(i => i.id);
  showApprovalModal.value = true;
};

const submitApproval = async () => {
  approving.value = true;
  try {
    await api.post(`/quotations/${quotation.value.id}/approve`, approvalForm.value);
    toast.success('Customer approval confirmed. Work Order generated successfully!');
    showApprovalModal.value = false;
    emit('updated');
    await fetchQuotation();
  } catch (err) {
    toast.error(err.response?.data?.message || 'Failed to confirm approval');
  } finally {
    approving.value = false;
  }
};

const formatCurrency = (value) => {
  return new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT' }).format(value || 0);
};

const formatDate = (dateString) => {
  if (!dateString) return '';
  const date = new Date(dateString);
  return date.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
};

const getQuotationStatusClass = (status) => {
  const map = {
    'draft': 'bg-slate-100 text-slate-800 border border-slate-300',
    'revised': 'bg-yellow-100 text-yellow-800 border border-yellow-300',
    'approved': 'bg-green-100 text-green-800 border border-green-300',
    'partially_approved': 'bg-blue-100 text-blue-800 border border-blue-300',
    'rejected': 'bg-red-100 text-red-800 border border-red-300',
  };
  return map[status] || 'bg-slate-100 text-slate-800';
};
</script>
